name: Analyze-Library

on:
  push:
    branches: [master]

jobs:
  lib-analysis:
    if: contains(github.event.head_commit.message, '[Start Analysis]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Execute analyzer
        run: |
          python ./rain_analyzer.py
      - name: Clone GitHub Pages Repository
        uses: actions/checkout@v3
        with:
          ref: json
          path: structure
      - name: Move openapi.json to gh folder
        run: mv analyzer_output/rain_structure.json structure
      - name: Update gh-pages branch
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: json
          FOLDER: structure
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Update json branch with commit {sha}"
