name: Create Bug Fix Branch

on:
  issues:
    types: [ labeled ]

jobs:
  create-branch:
    if: github.event.label.name == 'bug'
    runs-on: ubuntu-latest

    steps:
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "bug-fix-${{ github.event.issue.number }}"
